import React, { useState, useEffect } from 'react';
import { 
  Trash2, MessageCircle, DollarSign, Search, ClipboardList, 
  TrendingUp, Wallet
} from 'lucide-react';

const Orders = () => {
  // --- Data Retrieval ---
  const [orders, setOrders] = useState(() => {
    try {
      const saved = localStorage.getItem('studioOrders');
      return saved ? JSON.parse(saved) : [];
    } catch (e) { return []; }
  });

  const [inventory] = useState(() => {
    try {
        return JSON.parse(localStorage.getItem('studioInventory')) || [];
    } catch(e) { return []; }
  });

  const [customers] = useState(() => {
    try {
        return JSON.parse(localStorage.getItem('studioCustomers')) || [];
    } catch(e) { return []; }
  });

  // --- UI States ---
  const [selectedTime, setSelectedTime] = useState(new Date().toISOString().slice(0, 7)); 
  const [searchTerm, setSearchTerm] = useState(""); 
  const [showPinModal, setShowPinModal] = useState(false);
  const [activeOrder, setActiveOrder] = useState(null);
  const [modalAction, setModalAction] = useState(""); 
  const [pinInput, setPinInput] = useState("");
  const [payAmount, setPayAmount] = useState("");
  const [pendingStatus, setPendingStatus] = useState("");

  const SYSTEM_PIN = "1234";

  const [newOrder, setNewOrder] = useState({
    customerName: '', phone: '', dueDate: new Date().toISOString().split('T')[0], 
    size: '', frameType: '', frameColor: 'Black', priceType: 'Retail', totalPrice: 0, advance: 0, status: 'Pending'
  });

  useEffect(() => {
    localStorage.setItem('studioOrders', JSON.stringify(orders));
  }, [orders]);

  // --- Filtered List for Table ---
  const filteredOrders = orders.filter(o => 
    o?.dueDate?.startsWith(selectedTime) && 
    (o?.customerName?.toLowerCase().includes(searchTerm.toLowerCase()) || o.id?.toString().includes(searchTerm))
  );

  // --- Analytics Logic (Fixed Profit) ---
  const stats = orders.reduce((acc, o) => {
    const isThisMonth = o?.dueDate?.startsWith(selectedTime);
    const rev = Number(o.totalPrice || 0);
    
    // Find matching item for cost
    const item = inventory?.find(i => 
        String(i.type).trim().toLowerCase() === String(o.frameType).trim().toLowerCase() && 
        String(i.size).trim().toLowerCase() === String(o.size).trim().toLowerCase()
    );
    
    // Fallback: If no item found, assume 50% cost to avoid NaN
    const cost = item ? (Number(item.costPrice || item.wholesalePrice) || 0) : (rev * 0.5); 

    if (isThisMonth) {
      acc.monthlyOrders += 1;
      acc.revenue += rev;
      acc.profit += (rev - cost);
    }
    acc.totalBalance += Number(o.balance || 0);
    return acc;
  }, { monthlyOrders: 0, revenue: 0, totalBalance: 0, profit: 0 });

  // --- WhatsApp Logic ---
  const sendWhatsAppBill = (order, isNewOrder = false) => {
    if (!order.phone) return alert("Phone number missing!");
    const shortId = order.id ? order.id.toString().slice(-6) : "000000";
    let cleanPhone = order.phone.toString().replace(/\D/g, ''); 
    if (cleanPhone.startsWith('0')) cleanPhone = cleanPhone.substring(1);
    const finalPhone = cleanPhone.startsWith('94') ? cleanPhone : `94${cleanPhone}`;

    let message = "";
    if (isNewOrder) {
      message = `✨ *OFFICIAL RECEIPT*\n*GIFTY VIBE STUDIO*\n━━━━━━━━━━━━\n\n👤 *Customer:* ${order.customerName}\n🔢 *Order No:* #${shortId}\n📅 *Due Date:* ${order.dueDate}\n\n🖼️ *DETAILS*\n● Item: ${order.frameType}\n● Size: ${order.size}\n● Color: ${order.frameColor}\n● *Type: ${order.priceType}*\n\n💰 *PAYMENT SUMMARY*\n● Total Price: Rs.${Number(order.totalPrice).toLocaleString()}\n● Advance Paid: Rs.${Number(order.advance).toLocaleString()}\n● *Balance Due: Rs.${Number(order.balance).toLocaleString()}*\n\n━━━━━━━━━━━━\n🙏 *Thank you for choosing us!*`;
    } else if (order.status === "Delivered") {
      message = `✅ *ORDER DELIVERED*\n*GIFTY VIBE STUDIO*\n━━━━━━━━━━━━\n\n👤 *Customer:* ${order.customerName}\n🔢 *Order No:* #${shortId}\n\n🎁 Your order has been delivered! We hope you love it.\n\n━━━━━━━━━━━━`;
    } else if (order.status === "Completed") {
      message = `🎉 *ORDER IS READY!*\n*GIFTY VIBE STUDIO*\n━━━━━━━━━━━━\n\n👤 Dear ${order.customerName},\nYour order *#${shortId}* is now ready for pickup! 🖼️✨\n\n💳 *Balance to Pay: Rs.${Number(order.balance).toLocaleString()}*\n\n━━━━━━━━━━━━`;
    }

    const finalMsg = `${message}\n\n_Auto Generated by Gifty Vibe System_`;
    window.open(`https://wa.me/${finalPhone}?text=${encodeURIComponent(finalMsg)}`, '_blank');
  };

  const handleFormUpdate = (field, value) => {
    setNewOrder(prev => {
      let updated = { ...prev, [field]: value };
      if (field === 'customerName') {
        const c = customers?.find(cust => cust.name === value);
        updated.phone = c ? c.phone : '';
      }
      if (field === 'selection' || field === 'priceType') {
        const selectionVal = field === 'selection' ? value : (updated.frameType + "|" + updated.size);
        const [type, size] = selectionVal.split('|');
        const item = inventory?.find(i => i.type === type && i.size === size);
        updated.frameType = type || '';
        updated.size = size || '';
        if (item) {
          updated.totalPrice = updated.priceType === 'Wholesale' ? (Number(item.wholesalePrice) || 0) : (Number(item.retailPrice) || 0);
        }
      }
      return updated;
    });
  };

  const addOrder = (e) => {
    e.preventDefault();
    const orderData = { 
        ...newOrder, 
        id: Date.now(), 
        balance: Number(newOrder.totalPrice) - Number(newOrder.advance) 
    };
    setOrders([orderData, ...orders]);
    sendWhatsAppBill(orderData, true);
    setNewOrder({ ...newOrder, customerName: '', totalPrice: 0, advance: 0 });
  };

  const handlePinAction = () => {
    if (pinInput !== SYSTEM_PIN) return alert("Invalid PIN!");
    let updatedOrders = [...orders];
    if (modalAction === "STATUS") {
      updatedOrders = orders.map(o => o.id === activeOrder.id ? { ...o, status: pendingStatus } : o);
      const updatedO = updatedOrders.find(o => o.id === activeOrder.id);
      sendWhatsAppBill(updatedO);
    } else if (modalAction === "PAY") {
      const payAmt = Number(payAmount);
      updatedOrders = orders.map(o => o.id === activeOrder.id ? { 
        ...o, 
        advance: Number(o.advance) + payAmt, 
        balance: Number(o.balance) - payAmt 
      } : o);
    } else if (modalAction === "DELETE") {
      updatedOrders = orders.filter(o => o.id !== activeOrder.id);
    }
    setOrders(updatedOrders);
    setShowPinModal(false); setPinInput(""); setPayAmount("");
  };

  // --- Styles remain the same as your input ---
  // ... (keeping your provided styles for consistency)

  return (
    <div style={containerStyle}>
      <div style={headerStyle}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <ClipboardList size={28} />
          <h2 style={{ margin: 0 }}>Gifty Vibe Operations</h2>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <div style={searchContainer}>
            <Search size={16} style={searchIcon} />
            <input type="text" placeholder="Search..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} style={searchInput} />
          </div>
          <input type="month" value={selectedTime} onChange={(e) => setSelectedTime(e.target.value)} style={dateInputS} />
        </div>
      </div>

      <div style={dashGrid}>
        <div style={{...dashCard, background: '#fff1f2', border: '1px solid #f43f5e'}}>
          <div style={{...dashIcon, background: '#ffe4e6'}}><Wallet size={24} color="#f43f5e"/></div>
          <div><div style={labelS}>TOTAL BALANCE</div><div style={dashVal}>Rs.{stats.totalBalance.toLocaleString()}</div></div>
        </div>
        <div style={dashCard}><div style={{...dashIcon, background: '#eff6ff'}}><ClipboardList size={22} color="#3b82f6"/></div><div><div style={labelS}>MONTHLY ORDERS</div><div style={dashVal}>{stats.monthlyOrders}</div></div></div>
        <div style={dashCard}><div style={{...dashIcon, background: '#f0fdf4'}}><DollarSign size={22} color="#22c55e"/></div><div><div style={labelS}>MONTHLY REVENUE</div><div style={dashVal}>Rs.{stats.revenue.toLocaleString()}</div></div></div>
        <div style={dashCard}><div style={{...dashIcon, background: '#faf5ff'}}><TrendingUp size={22} color="#8b5cf6"/></div><div><div style={labelS}>EST. PROFIT</div><div style={{...dashVal, color: '#22c55e'}}>Rs.{stats.profit.toLocaleString()}</div></div></div>
      </div>

      <form onSubmit={addOrder} style={formCard}>
        <div style={formGrid}>
          <div style={inputGroup}><label style={labelS}>CUSTOMER</label>
            <select style={inputS} value={newOrder.customerName} onChange={e => handleFormUpdate('customerName', e.target.value)} required>
              <option value="">Select Customer</option>
              {customers?.map(c => <option key={c.id} value={c.name}>{c.name}</option>)}
            </select>
          </div>
          <div style={inputGroup}><label style={labelS}>DUE DATE</label>
            <input type="date" style={inputS} value={newOrder.dueDate} onChange={e => handleFormUpdate('dueDate', e.target.value)} required />
          </div>
          <div style={inputGroup}><label style={labelS}>ITEM & SIZE</label>
            <select style={inputS} onChange={e => handleFormUpdate('selection', e.target.value)} required>
              <option value="">Select Item</option>
              {inventory?.map(f => <option key={f.id} value={`${f.type}|${f.size}`}>{f.type} ({f.size})</option>)}
            </select>
          </div>
          <div style={inputGroup}><label style={labelS}>COLOR</label>
            <select style={inputS} value={newOrder.frameColor} onChange={e => handleFormUpdate('frameColor', e.target.value)}>
              <option value="Black">Black</option><option value="Gold">Gold</option><option value="White">White</option><option value="Wood">Wood</option>
            </select>
          </div>
          <div style={inputGroup}><label style={labelS}>PRICE TYPE</label>
            <div style={toggleContainer}>
              <button type="button" onClick={() => handleFormUpdate('priceType', 'Retail')} style={priceToggleBtn(newOrder.priceType === 'Retail', '#3b82f6')}>Retail</button>
              <button type="button" onClick={() => handleFormUpdate('priceType', 'Wholesale')} style={priceToggleBtn(newOrder.priceType === 'Wholesale', '#8b5cf6')}>Wholesale</button>
            </div>
          </div>
          <div style={priceBox}><small style={labelS}>TOTAL</small><br/><b>Rs.{newOrder.totalPrice.toLocaleString()}</b></div>
          <div style={inputGroup}><label style={labelS}>ADVANCE</label>
            <input type="number" style={inputS} value={newOrder.advance} onChange={e => handleFormUpdate('advance', e.target.value)} required />
          </div>
          <button type="submit" style={submitBtn}>Confirm Order</button>
        </div>
      </form>

      <div style={tableWrapper}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: '#f8fafc', borderBottom: '1px solid #e2e8f0' }}>
              <th style={thS}>Order Info</th>
              <th style={thS}>Details</th>
              <th style={thS}>Color</th>
              <th style={thS}>Due Date</th>
              <th style={thS}>Total</th>
              <th style={thS}>Advance</th>
              <th style={thS}>Balance</th>
              <th style={thS}>Status</th>
              <th style={thS}>Action</th>
            </tr>
          </thead>
          <tbody>
            {filteredOrders.map(o => (
              <tr key={o.id} style={{ borderBottom: '1px solid #f1f5f9', background: o.status === 'Pending' ? '#fff1f2' : 'transparent' }}>
                <td style={tdS}>
                  <b>{o.customerName}</b><br/>
                  <small style={{color: '#64748b', fontSize: '10px'}}>{o.priceType} | #{o.id.toString().slice(-6)}</small>
                </td>
                <td style={tdS}>{o.frameType} ({o.size})</td>
                <td style={tdS}>{o.frameColor}</td>
                <td style={tdS}>{o.dueDate}</td>
                <td style={tdS}>Rs.{Number(o.totalPrice).toLocaleString()}</td>
                <td style={tdS}>Rs.{Number(o.advance).toLocaleString()}</td>
                <td style={{...tdS, color: o.balance > 0 ? '#ef4444' : '#22c55e', fontWeight: 'bold'}}>Rs.{Number(o.balance).toLocaleString()}</td>
                <td style={tdS}>
                  <select value={o.status} onChange={(e) => { setActiveOrder(o); setPendingStatus(e.target.value); setModalAction("STATUS"); setShowPinModal(true); }} style={statusBtn(o.status)}>
                    <option value="Pending">Pending</option><option value="Completed">Ready</option><option value="Delivered">Delivered</option>
                  </select>
                </td>
                <td style={tdS}>
                   <button onClick={() => sendWhatsAppBill(o)} style={actionBtn}><MessageCircle size={16}/></button>
                   <button onClick={() => { setActiveOrder(o); setModalAction("PAY"); setPayAmount(o.balance); setShowPinModal(true); }} style={actionBtn}><DollarSign size={16}/></button>
                   <button onClick={() => { setActiveOrder(o); setModalAction("DELETE"); setShowPinModal(true); }} style={{ ...actionBtn, color: '#ef4444' }}><Trash2 size={16}/></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {showPinModal && (
        <div style={modalOverlay}>
          <div style={modalContent}>
            <h3>{modalAction === "PAY" ? "Receive Payment" : "Verification"}</h3>
            {modalAction === "PAY" && (
              <input type="number" style={pinInputStyle} value={payAmount} onChange={e => setPayAmount(e.target.value)} />
            )}
            <input type="password" style={pinInputStyle} value={pinInput} onChange={e => setPinInput(e.target.value)} maxLength={4} placeholder="PIN" />
            <div style={{ display: 'flex', gap: '10px', marginTop: '10px' }}>
              <button onClick={handlePinAction} style={confirmBtn}>Confirm</button>
              <button onClick={() => setShowPinModal(false)} style={closeBtn}>Cancel</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// --- Styles (Original styles maintained) ---
const containerStyle = { padding: '30px', background: '#f8fafc', minHeight: '100vh', fontFamily: 'Inter, sans-serif' };
const headerStyle = { background: '#0f172a', padding: '20px', borderRadius: '15px', color: 'white', marginBottom: '20px', display: 'flex', justifyContent: 'space-between' };
const dashGrid = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '15px', marginBottom: '25px' };
const dashCard = { background: 'white', padding: '15px', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '15px', border: '1px solid #e2e8f0' };
const dashIcon = { padding: '10px', borderRadius: '10px' };
const dashVal = { fontSize: '18px', fontWeight: '800' };
const labelS = { fontSize: '10px', color: '#64748b', fontWeight: 'bold' };
const searchContainer = { position: 'relative', display: 'flex', alignItems: 'center' };
const searchIcon = { position: 'absolute', left: '10px', color: '#94a3b8' };
const searchInput = { padding: '8px 8px 8px 35px', borderRadius: '8px', border: 'none', width: '150px' };
const dateInputS = { padding: '8px', borderRadius: '8px', border: 'none' };
const formCard = { background: 'white', padding: '20px', borderRadius: '15px', marginBottom: '20px', border: '1px solid #e2e8f0' };
const formGrid = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: '12px', alignItems: 'flex-end' };
const inputGroup = { display: 'flex', flexDirection: 'column', gap: '5px' };
const inputS = { padding: '8px', borderRadius: '8px', border: '1px solid #e2e8f0' };
const priceBox = { padding: '8px', background: '#f8fafc', borderRadius: '10px', textAlign: 'center' };
const submitBtn = { padding: '10px', background: '#3b82f6', color: 'white', border: 'none', borderRadius: '10px', fontWeight: 'bold', cursor: 'pointer' };
const tableWrapper = { background: 'white', borderRadius: '15px', border: '1px solid #e2e8f0', overflow: 'hidden' };
const thS = { padding: '12px', textAlign: 'left', fontSize: '11px', color: '#64748b' };
const tdS = { padding: '12px', fontSize: '13px' };
const actionBtn = { background: '#f1f5f9', border: 'none', padding: '8px', borderRadius: '8px', marginLeft: '5px', cursor: 'pointer' };
const statusBtn = (s) => ({ padding: '5px', borderRadius: '5px', border: 'none', fontSize: '11px', fontWeight: 'bold', background: s==='Completed'?'#dcfce7':'#fef9c3' });
const toggleContainer = { display: 'flex', background: '#f1f5f9', padding: '3px', borderRadius: '8px' };
const priceToggleBtn = (active, col) => ({ flex: 1, padding: '5px', border: 'none', borderRadius: '6px', fontSize: '10px', background: active?col:'transparent', color: active?'white':'#64748b' });
const modalOverlay = { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', justifyContent: 'center', alignItems: 'center' };
const modalContent = { background: 'white', padding: '25px', borderRadius: '15px', textAlign: 'center', width: '280px' };
const pinInputStyle = { width: '80%', padding: '10px', fontSize: '16px', textAlign: 'center', borderRadius: '10px', border: '1px solid #ddd', marginBottom: '10px' };
const confirmBtn = { flex: 1, padding: '10px', background: '#3b82f6', color: 'white', border: 'none', borderRadius: '8px' };
const closeBtn = { flex: 1, padding: '10px', background: '#f1f5f9', border: 'none', borderRadius: '8px' };

export default Orders;